# /// script
# dependencies = ["fonttools", "pillow"]
# ///
"""Regenerate KOVVBOJ's icon set in packaging/.

    uv run .github/packaging/app_icon.py

Writes icon.svg (source), AppIcon.icns (macOS bundle), icon.ico (Windows
shortcut) and icon-256.png (runtime window icon, see rustjay_engine::set_window_icon).
Needs `resvg` (brew install resvg) and macOS `iconutil`.

House style: Workbench glyphs outlined to paths on a macOS squircle, magenta
#FA32C1 art, red #F74031 halation + wide magenta bloom, scanlines, vignette.
Shared house style with the rustjay-engine apps (vp404 etc.), whose copy of this
script lives in that repo.
"""
import subprocess
import tempfile
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
FONT = TTFont(ROOT / "assets/fonts/Workbench.ttf")
GLYPHS = FONT.getGlyphSet()
CMAP = FONT.getBestCmap()


def text(s, cx, cy, width, tracking=0, squash=1.0):
    """Workbench `s` as paths, ink centred on (cx, cy), ink `width` wide."""
    paths, bounds, x = [], BoundsPen(GLYPHS), 0
    for ch in s:
        g = GLYPHS[CMAP[ord(ch)]]
        pen = SVGPathPen(GLYPHS)
        g.draw(pen)
        g.draw(TransformPen(bounds, (1, 0, 0, 1, x, 0)))
        paths.append(f'<path transform="translate({x} 0)" d="{pen.getCommands()}"/>')
        x += g.width + tracking
    x0, y0, x1, y1 = bounds.bounds
    sx = width / (x1 - x0)
    sy = sx * squash
    tx, ty = cx - sx * (x0 + x1) / 2, cy + sy * (y0 + y1) / 2
    return f'<g transform="translate({tx:.2f} {ty:.2f}) scale({sx:.4f} {-sy:.4f})">{"".join(paths)}</g>'


def icon(lit, dim=""):
    """`lit` glows (halation + bloom), `dim` sits unlit behind it."""
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<!-- Generated by .github/packaging/app_icon.py; edit that, not this. Workbench glyphs (OFL). -->
<defs>
  <clipPath id="sq"><rect x="100" y="100" width="824" height="824" rx="185"/></clipPath>
  <symbol id="lit" overflow="visible">{lit}</symbol>
  <filter id="h0" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="14"/></filter>
  <filter id="h1" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="60"/></filter>
  <pattern id="scan" width="8" height="8" patternUnits="userSpaceOnUse"><rect y="5" width="8" height="3" fill="#000" opacity="0.45"/></pattern>
  <radialGradient id="vig" cx="50%" cy="50%" r="62%"><stop offset="55%" stop-color="#000" stop-opacity="0"/><stop offset="100%" stop-color="#000" stop-opacity="0.75"/></radialGradient>
</defs>
<g clip-path="url(#sq)">
  <rect width="1024" height="1024" fill="#0c0c10"/>
  <g fill="#FA32C1" opacity="0.16">{dim}</g>
  <use href="#lit" fill="#FA32C1" opacity="0.35" filter="url(#h1)"/>
  <use href="#lit" fill="#F74031" opacity="0.85" filter="url(#h0)"/>
  <use href="#lit" fill="#FA32C1"/>
  <rect width="1024" height="1024" fill="url(#scan)"/>
  <rect width="1024" height="1024" fill="url(#vig)"/>
</g>
</svg>'''




def main():
    out = ROOT / "packaging"
    svg = out / "icon.svg"
    svg.write_text(icon(text("KVJ", 512, 512, 618)))

    def render(width, path):
        subprocess.run(["resvg", "-w", str(width), svg, path], check=True)

    render(256, out / "icon-256.png")
    with tempfile.TemporaryDirectory() as tmp:
        iconset = Path(tmp) / "AppIcon.iconset"
        iconset.mkdir()
        for s in (16, 32, 128, 256, 512):
            render(s, iconset / f"icon_{s}x{s}.png")
            render(s * 2, iconset / f"icon_{s}x{s}@2x.png")
        subprocess.run(["iconutil", "-c", "icns", iconset, "-o", out / "AppIcon.icns"], check=True)
        Image.open(iconset / "icon_512x512@2x.png").save(
            out / "icon.ico", sizes=[(16, 16), (32, 32), (48, 48), (256, 256)])
    print(f"wrote {out}/{{icon.svg,icon-256.png,AppIcon.icns,icon.ico}}")


if __name__ == "__main__":
    main()
